<?php

if ( !defined( 'ABSPATH' ) ) {
	return array();
}

return apply_filters( 'bpmj_eddcm_layout_default_color_presets', array(
    'default'	 => array(
	'label'	 => __( 'Default', BPMJ_EDDCM_DOMAIN ),
	'data'	 => array(
	    /* primary colors */
	    'alternative_bg_color'		 => '#f1f1f8',
	    'bg_color'			 => '#ffffff',
	    'border_color'			 => '#e0e4ec',
	    'primary_color'			 => '#92cdcf',
	    'text_color'			 => '#1c1d21',
	    /* secondary colors */
	    'box_bg_color'			 => '#f1f1f8',
	    'box_border_color'		 => '#e0e4ec',
	    'box_text_color'		 => '#1c1d21',
	    'button_bg_color'		 => '#445878',
	    'button_border_color'		 => '#344868',
	    'contrast_text_color'		 => '#ffffff',
	    'footer_alt_bg_color'		 => '#344868',
	    'footer_alt_text_color'		 => '#ffffff',
	    'footer_bg_color'		 => '#344868',
	    'footer_links_color'		 => '#81c0c2',
	    'footer_links_hover_color'	 => '#81c0c2',
	    'footer_text_color'		 => '#ffffff',
	    'form_button_bg_color'		 => '#e0e4ec',
	    'form_button_border_color'	 => '#ced4e0',
	    'header_bg_color'		 => '#f1f1f8',
	    'highlight_color'		 => '#ffffff',
	    'input_bg_color'		 => '#f1f1f8',
	    'input_border_color'		 => '#e0e4ec',
	    'input_text_color'		 => '#1c1d21',
	    'links_color'			 => '#81c0c2',
	    'links_color_alt'		 => '#81c0c2',
	    'menu_icon_color'		 => '#e0e4ec',
	    'order_form_bg_color'		 => '#ffffff',
	    'order_form_button_border_color' => '#ced4e0',
	    'order_form_button_text_color'	 => '#1c1d21',
	    'order_form_text_color'		 => '#1c1d21',
	    'placeholder_text_color'	 => '#bdc3ce',
	    'section_text_color'		 => '#1c1d21',
	    'thumb_bg_color'		 => '#e0e4ec',
	    'thumb_border_color'		 => '#ced4e0',
	),
    ),
    'preset-1'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 1 ),
	'data'	 => array(
	    /* primary colors */
	    'alternative_bg_color'		 => '#232020',
	    'bg_color'			 => '#e9eaea',
	    'border_color'			 => '#c5c4c4',
	    'primary_color'			 => '#7494ca',
	    'text_color'			 => '#232021',
	    /* secondary colors */
	    'box_bg_color'			 => '#dedede',
	    'box_border_color'		 => '#c5c4c4',
	    'box_text_color'		 => '#232021',
	    'button_bg_color'		 => '#7494CA',
	    'button_border_color'		 => '#546c93',
	    'contrast_text_color'		 => '#ffffff',
	    'footer_alt_bg_color'		 => '#e9eaea',
	    'footer_alt_text_color'		 => '#232021',
	    'footer_bg_color'		 => '#232020',
	    'footer_links_color'		 => '#7494ca',
	    'footer_links_hover_color'	 => '#7494ca',
	    'footer_text_color'		 => '#ffffff',
	    'form_button_bg_color'		 => '#dedede',
	    'form_button_border_color'	 => '#c5c4c4',
	    'header_bg_color'		 => '#232020',
	    'highlight_color'		 => '#faf9f5',
	    'input_bg_color'		 => '#dedede',
	    'input_border_color'		 => '#dedede',
	    'input_text_color'		 => '#232021',
	    'links_color'			 => '#7494ca',
	    'links_color_alt'		 => '#7494ca',
	    'menu_icon_color'		 => '#c5c4c4',
	    'order_form_bg_color'		 => '#e9eaea',
	    'order_form_button_border_color' => '#c5c4c4',
	    'order_form_button_text_color'	 => '#232021',
	    'order_form_text_color'		 => '#232021',
	    'placeholder_text_color'	 => '#c5c4c4',
	    'section_text_color'		 => '#f6f6f6',
	    'thumb_bg_color'		 => '#e9eaea',
	    'thumb_border_color'		 => '#c5c4c4',
	),
    ),
    'preset-2'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 2 ),
	'data'	 => array(
	    /* primary colors */
	    'alternative_bg_color'		 => '#e9e2d5',
	    'bg_color'			 => '#ffffff',
	    'border_color'			 => '#d9cdb8',
	    'primary_color'			 => '#dfb70c',
	    'text_color'			 => '#24211c',
	    /* secondary colors */
	    'box_bg_color'			 => '#e9e2d5',
	    'box_border_color'		 => '#d9cdb8',
	    'box_text_color'		 => '#24211c',
	    'button_bg_color'		 => '#dfb70c',
	    'button_border_color'		 => '#c6a20b',
	    'contrast_text_color'		 => '#24211c',
	    'footer_alt_bg_color'		 => '#d9cdb8',
	    'footer_alt_text_color'		 => '#24211c',
	    'footer_bg_color'		 => '#d9cdb8',
	    'footer_links_color'		 => '#24211c',
	    'footer_links_hover_color'	 => '#24211c',
	    'footer_text_color'		 => '#24211c',
	    'form_button_bg_color'		 => '#d9cdb8',
	    'form_button_border_color'	 => '#857565',
	    'header_bg_color'		 => '#e9e2d5',
	    'highlight_color'		 => '#ffffff',
	    'input_bg_color'		 => '#e9e2d5',
	    'input_border_color'		 => '#d9cdb8',
	    'input_text_color'		 => '#24211c',
	    'links_color'			 => '#dfb70c',
	    'links_color_alt'		 => '#dfb70c',
	    'menu_icon_color'		 => '#d9cdb8',
	    'order_form_bg_color'		 => '#ffffff',
	    'order_form_button_border_color' => '#857565',
	    'order_form_button_text_color'	 => '#24211c',
	    'order_form_text_color'		 => '#24211c',
	    'placeholder_text_color'	 => '#d9cdb8',
	    'section_text_color'		 => '#24211c',
	    'thumb_bg_color'		 => '#d9cdb8',
	    'thumb_border_color'		 => '#857565',
	),
    ),
    'preset-3'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 3 ),
	'data'	 => array(
	    'bg_file'			 => '../gfx/background.jpg',
	    /* primary colors */
	    'alternative_bg_color'		 => '#f3f0e8',
	    'bg_color'			 => '#ffffff',
	    'border_color'			 => '#d9d0ba',
	    'primary_color'			 => '#8c9a00',
	    'text_color'			 => '#1d1d1d',
	    /* secondary colors */
	    'box_bg_color'			 => '#f3f0e8',
	    'box_border_color'		 => '#d9d0ba',
	    'box_text_color'		 => '#1d1d1d',
	    'button_bg_color'		 => '#c7da00',
	    'button_border_color'		 => '#afc100',
	    'contrast_text_color'		 => '#1d1d1d',
	    'footer_alt_bg_color'		 => '#d9d0ba',
	    'footer_alt_text_color'		 => '#1d1d1d',
	    'footer_bg_color'		 => '#d9d0ba',
	    'footer_links_color'		 => '#1d1d1d',
	    'footer_links_hover_color'	 => '#353129',
	    'footer_text_color'		 => '#1d1d1d',
	    'form_button_bg_color'		 => '#ece6d8',
	    'form_button_border_color'	 => '#d9d0ba',
	    'header_bg_color'		 => '#f3f0e8',
	    'highlight_color'		 => '#ffffff',
	    'input_bg_color'		 => '#f3f0e8',
	    'input_border_color'		 => '#d9d0ba',
	    'input_text_color'		 => '#1d1d1d',
	    'links_color'			 => '#8c9a00',
	    'links_color_alt'		 => '#8c9a00',
	    'menu_icon_color'		 => '#d9d0ba',
	    'order_form_bg_color'		 => '#ffffff',
	    'order_form_button_border_color' => '#d9d0ba',
	    'order_form_button_text_color'	 => '#1d1d1d',
	    'order_form_text_color'		 => '#1d1d1d',
	    'placeholder_text_color'	 => '#d9d0ba',
	    'section_text_color'		 => '#1d1d1d',
	    'thumb_bg_color'		 => '#ece6d8',
	    'thumb_border_color'		 => '#d9d0ba',
	),
    ),
    'preset-4'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 4 ),
	'data'	 => array(
	    'bg_file'			 => '../gfx/background.jpg',
	    /* primary colors */
	    'alternative_bg_color'		 => '#2d2d32',
	    'bg_color'			 => '#faf9f5',
	    'border_color'			 => '#d5d5d0',
	    'primary_color'			 => '#50c8a2',
	    'text_color'			 => '#1d1d1d',
	    /* secondary colors */
	    'box_bg_color'			 => '#f6f5f1',
	    'box_border_color'		 => '#d5d5d0',
	    'box_text_color'		 => '#1d1d1d',
	    'button_bg_color'		 => '#54a3bb',
	    'button_border_color'		 => '#368ba5',
	    'contrast_text_color'		 => '#faf9f5',
	    'footer_alt_bg_color'		 => '#faf9f5',
	    'footer_alt_text_color'		 => '#1d1d1d',
	    'footer_bg_color'		 => '#2d2d32',
	    'footer_links_color'		 => '#54a3bb',
	    'footer_links_hover_color'	 => '#54a3bb',
	    'footer_text_color'		 => '#faf9f5',
	    'form_button_bg_color'		 => '#2d2d32',
	    'form_button_border_color'	 => '#d5d5d0',
	    'header_bg_color'		 => '#2d2d32',
	    'highlight_color'		 => '#faf9f5',
	    'input_bg_color'		 => '#f6f5f1',
	    'input_border_color'		 => '#d5d5d0',
	    'input_text_color'		 => '#1d1d1d',
	    'links_color'			 => '#54a3bb',
	    'links_color_alt'		 => '#54a3bb',
	    'menu_icon_color'		 => '#d5d5d0',
	    'order_form_bg_color'		 => '#faf9f5',
	    'order_form_button_border_color' => '#1d1d1d',
	    'order_form_button_text_color'	 => '#faf9f5',
	    'order_form_text_color'		 => '#1d1d1d',
	    'placeholder_text_color'	 => '#d5d5d0',
	    'section_text_color'		 => '#faf9f5',
	    'thumb_bg_color'		 => '#f6f5f1',
	    'thumb_border_color'		 => '#d5d5d0',
	),
    ),
    'preset-5'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 5 ),
	'data'	 => array(
	    /* primary colors */
	    'alternative_bg_color'		 => '#e7e7e7',
	    'bg_color'			 => '#f4f4f4',
	    'border_color'			 => '#d7d7d7',
	    'primary_color'			 => '#ff9527',
	    'text_color'			 => '#232021',
	    /* secondary colors */
	    'box_bg_color'			 => '#e7e7e7',
	    'box_border_color'		 => '#d7d7d7',
	    'box_text_color'		 => '#232021',
	    'button_bg_color'		 => '#ff9527',
	    'button_border_color'		 => '#ef800d',
	    'contrast_text_color'		 => '#f4f4f4',
	    'footer_alt_bg_color'		 => '#f4f4f4',
	    'footer_alt_text_color'		 => '#232021',
	    'footer_bg_color'		 => '#e7e7e7',
	    'footer_links_color'		 => '#ff9527',
	    'footer_links_hover_color'	 => '#ff9527',
	    'footer_text_color'		 => '#232021',
	    'form_button_bg_color'		 => '#ff9527',
	    'form_button_border_color'	 => '#d7d7d7',
	    'header_bg_color'		 => '#e7e7e7',
	    'highlight_color'		 => '#f4f4f4',
	    'input_bg_color'		 => '#e7e7e7',
	    'input_border_color'		 => '#d7d7d7',
	    'input_text_color'		 => '#232021',
	    'links_color'			 => '#ff9527',
	    'links_color_alt'		 => '#ff9527',
	    'menu_icon_color'		 => '#d7d7d7',
	    'order_form_bg_color'		 => '#f4f4f4',
	    'order_form_button_border_color' => '#ef800d',
	    'order_form_button_text_color'	 => '#f4f4f4',
	    'order_form_text_color'		 => '#232021',
	    'placeholder_text_color'	 => '#d7d7d7',
	    'section_text_color'		 => '#232021',
	    'thumb_bg_color'		 => '#f4f4f4',
	    'thumb_border_color'		 => '#d7d7d7',
	),
    ),
    'preset-6'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 6 ),
	'data'	 => array(
	    'section_bg_file'		 => '../gfx/section_background.jpg',
	    /* primary colors */
	    'alternative_bg_color'		 => '#acfc7e',
	    'bg_color'			 => '#ffffff',
	    'border_color'			 => '#90e266',
	    'primary_color'			 => '#46c588',
	    'text_color'			 => '#231f20',
	    /* secondary colors */
	    'box_bg_color'			 => '#f7efff',
	    'box_border_color'		 => '#f1e2fd',
	    'box_text_color'		 => '#231f20',
	    'button_bg_color'		 => '#46c588',
	    'button_border_color'		 => '#41b87f',
	    'contrast_text_color'		 => '#ffffff',
	    'footer_alt_bg_color'		 => '#ffffff',
	    'footer_alt_text_color'		 => '#231f20',
	    'footer_bg_color'		 => '#acfc7e',
	    'footer_links_color'		 => '#46C588',
	    'footer_links_hover_color'	 => '#46C588',
	    'footer_text_color'		 => '#231f20',
	    'form_button_bg_color'		 => '#acfc7e',
	    'form_button_border_color'	 => '#90e266',
	    'header_bg_color'		 => '#acfc7e',
	    'highlight_color'		 => '#90E266',
	    'input_bg_color'		 => '#ffffff',
	    'input_border_color'		 => '#90e266',
	    'input_text_color'		 => '#231f20',
	    'links_color'			 => '#46C588',
	    'links_color_alt'		 => '#46C588',
	    'menu_icon_color'		 => '#b8fc57',
	    'order_form_bg_color'		 => '#ffffff',
	    'order_form_button_border_color' => '#90e266',
	    'order_form_button_text_color'	 => '#231f20',
	    'order_form_text_color'		 => '#231f20',
	    'placeholder_text_color'	 => '#90e266',
	    'section_text_color'		 => '#231f20',
	    'thumb_bg_color'		 => '#ffffff',
	    'thumb_border_color'		 => '#90e266',
	),
    ),
    'preset-7'	 => array(
	'label'	 => sprintf( __( 'Preset %1$s', BPMJ_EDDCM_DOMAIN ), 7 ),
	'data'	 => array(
	    /* primary colors */
	    'alternative_bg_color'		 => '#fbfbf9',
	    'bg_color'			 => '#222222',
	    'border_color'			 => '#aca483',
	    'primary_color'			 => '#d3c9a1',
	    'text_color'			 => '#fbfbf9',
	    /* secondary colors */
	    'box_bg_color'			 => '#fbfbf9',
	    'box_border_color'		 => '#aca483',
	    'box_text_color'		 => '#222222',
	    'button_bg_color'		 => '#d3c9a1',
	    'button_border_color'		 => '#aca483',
	    'contrast_text_color'		 => '#222222',
	    'footer_alt_bg_color'		 => '#222222',
	    'footer_alt_text_color'		 => '#fbfbf9',
	    'footer_bg_color'		 => '#fbfbf9',
	    'footer_links_color'		 => '#d3c9a1',
	    'footer_links_hover_color'	 => '#d3c9a1',
	    'footer_text_color'		 => '#222222',
	    'form_button_bg_color'		 => '#d3c9a1',
	    'form_button_border_color'	 => '#aca483',
	    'header_bg_color'		 => '#fbfbf9',
	    'highlight_color'		 => '#aca483',
	    'input_bg_color'		 => '#222222',
	    'input_border_color'		 => '#d3c9a1',
	    'input_text_color'		 => '#fbfbf9',
	    'links_color'			 => '#ebe0b2',
	    'links_color_alt'		 => '#d3c9a1',
	    'menu_icon_color'		 => '#aca483',
	    'order_form_bg_color'		 => '#fbfbf9',
	    'order_form_button_border_color' => '#aca483',
	    'order_form_button_text_color'	 => '#222222',
	    'order_form_text_color'		 => '#222222',
	    'placeholder_text_color'	 => '#d3c9a1',
	    'section_text_color'		 => '#222222',
	    'thumb_bg_color'		 => '#d3c9a1',
	    'thumb_border_color'		 => '#aca483',
	),
    ),
    'custom'	 => array(
	'label' => __( 'Custom', BPMJ_EDDCM_DOMAIN ),
    ),
	)
);
