<?php

/*
  Plugin Name: Easy Digital Downloads - Auto Register Custom
  Plugin URI:
  Description: Wtyczka modyfikuje domyślne ustawienia EDD Auto Register
  Version: 1.0
  Author: upSell.pl & Better Profits
  Author URI: http://upsell.pl
 */

if ( !defined( 'BPMJ_UPSELL_STORE_URL' ) ) {
	define( 'BPMJ_UPSELL_STORE_URL', 'http://upsell.pl' );
}
define( 'BPMJ_EDD_ARC_NAME', 'EDD Auto Register Custom' );

define( 'BPMJ_EDD_ARC_PATH', dirname( __FILE__ ) ); // Katalog wtyczki
// Opcje. EDD -> ustawienia -> Extensions
require_once( BPMJ_EDD_ARC_PATH . '/includes/settings.php' );

global $edd_options;

function bpmj_edd_auto_register_custom_email_subject( $subject ) {
	global $edd_options;

	$default = 'Twoje dane logowania do ' . get_option( 'blogname' );
	$subject = empty( $edd_options[ 'bpmj_edd_arc_subject' ] ) ? $default : $edd_options[ 'bpmj_edd_arc_subject' ];

	return $subject;
}

add_filter( 'edd_auto_register_email_subject', 'bpmj_edd_auto_register_custom_email_subject' );

function bpmj_edd_auto_register_email_body( $default_email_body, $first_name, $username, $password ) {

	global $edd_options;

	$default = "Dzień dobry {firstname},\n\n";
	$default .= "Twoje zamówienie zostało przyjęte.\n\n";
	$default .= "Utworzyliśmy dla Ciebie konto na platformie " . get_option( 'blogname' ) . ". Oto Twoje dane logowania:\n\n";
	$default .= "Login: {login}\n";
    $default .= 'Link do ustawienia hasła: <a href="{password_reset_link}">{password_reset_link}</a>\n\n';
	$default .= "-- \n";
	$default .= "Wiadomość wygenerowana automatycznie.\n";
	$default .= get_option( 'siteurl' ) . "\r\n";

	$default_email_body	 = empty( $edd_options[ 'bpmj_edd_arc_content' ] ) ? $default : $edd_options[ 'bpmj_edd_arc_content' ];

	$default_email_body	 = str_replace( '{firstname}', $first_name, $default_email_body );
	$default_email_body	 = str_replace( '{login}', $username, $default_email_body );
	$default_email_body	 = str_replace( '{password}', $password, $default_email_body );

	return $default_email_body;
}

add_filter( 'edd_auto_register_email_body', 'bpmj_edd_auto_register_email_body', 10, 4 );

/**
 * Provides simpler, friendlier auto-generated passwords, such as pAvULyNofE
 *
 * @param int $length
 *
 * @return string
 */
function bpmj_edd_auto_register_generate_password( $length = 10 ) {
	$vowels         = 'aeiouy';
	$vowels_max     = strlen( $vowels ) - 1;
	$consonants     = 'bcdfghjklmnpqrstvwxz';
	$consonants_max = strlen( $consonants ) - 1;
	$password       = '';
	for ( $i = 0; $i < $length; ++ $i ) {
		if ( 0 === $i % 2 ) {
			$char = substr( $consonants, wp_rand( 0, $consonants_max ), 1 );
		} else {
			$char = substr( $vowels, wp_rand( 0, $vowels_max ), 1 );
		}
		if ( 0 === wp_rand( 0, 1 ) ) {
			$char = strtoupper( $char );
		}
		$password .= $char;
	}

	return $password;
}

/**
 * Filters user params before they get inserted to the database
 *
 * @param array $args
 *
 * @return mixed
 */
function bpmj_edd_auto_register_insert_user_args( $args ) {
	/*
	 * Simplify autogenerated password (32 characters is too much)
	 */
	$args[ 'user_pass' ] = bpmj_edd_auto_register_generate_password();

	return $args;
}

add_filter( 'edd_auto_register_insert_user_args', 'bpmj_edd_auto_register_insert_user_args' );
